### PR TITLE
Check for and remove "RTC" drive prefix when returning selected file path added by the jupyter-collaboration 

### LINKED ISSUE #429: Input Path with Prefix "RTC:" breaking functionality
## Description

With both `jupyter-collaboration` and `jupyter_scheduler` extensions installed, `jupyter_scheduler` will detect `notebook.ipynb` as `RTC:notebook.ipynb` which causes `jupyter_scheduler` failing to find the file in path, the file path URL will also look something like this: "localhost:8080/user/user1/lab/tree/RTC%3Anotebook.ipynb"

Weirdly I also noticed "RTC:" in the launcher tab as well.

Initial issue in `jupyter-collaboration` repo: https://github.com/jupyterlab/jupyter-collaboration/issues/183#issuecomment-1697679929

## Reproduce

1. Install the following libraries in Python 3.11.4
```
conda install jupyter-collaboration=1.0.1
pip install jupyter_scheduler==2.0.0 jupyterlab==4.0.4
```
2. Start jupyterlab with
```
jupyter lab
```

## Expected behavior

Filename to not be changed and "RTC:" prefix not showing in launcher tab. And is able to schedule notebook correctly.

## Context

- Operating System and version: MacOS Ventura 13.4 
- Browser and version: Edge 114.01823.82 
- JupyterLab version: 4.0.4 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

image
image

</details>

### PR DESCRIPTION
**Pull request by andrii-i**
## References

- Fixes #429 
- JupyterLab reference PR fixing inability to create files in custom drives (everytime a file path is being handled, it should be assumed there can be a drive prefix in the file name) https://github.com/jupyterlab/jupyterlab/pull/15291/files#diff-a05e6e7e60f1adc4ea4f416f51df2d1e0277a12b5c84dea329859c9ccd6aef96R412-R427
- JupyterLab work in progress PR that would remove the need for special handling of drive prefixes (won't be in JupyterLab 4.3, JupyterLab 4.4 earliest) https://github.com/jupyterlab/jupyterlab/pull/16556

## Code changes

`getSelectedFilePath` helper function now uses `serviceManager.contents` API to check if there is an added “RTC” drive name in the file path and return local path without it.

## User-facing changes

Jupyter Scheduler now works when `jupyter-collaboration` is installed.

## Backwards-incompatible changes

None

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -260,7 +268,8 @@ function activatePlugin(
     execute: async () => {
       eventLogger('file-browser.create-job');
       const widget = fileBrowserTracker.currentWidget;
-      const filePath = getSelectedFilePath(widget) ?? '';
+      const filePath = getSelectedFilePath(widget, app) ?? '';
+      console.log(filePath);
```
Comment (dlqqq) [inline src/index.tsx:272]: Can this console log statement be removed?

**Review by dlqqq — CHANGES_REQUESTED** [review]

**Comment by dlqqq** [comment]
@andrii-i Can you also post a link to the JupyterLab PR that provided the `getLocalPath()` reference implementation as a comment on this PR?

**Comment by andrii-i** [comment]
@dlqqq thank you for looking into this. I added links to reference PRs into the PR description.

**Comment by sravyasdh** [comment]
Tested in both Sagemaker Studio private and shared spaces, the fix works great.

**Comment by andrii-i** [comment]
Thank you everyone for looking into this.
