### PR TITLE
Error alerts in list job definitions view

### LINKED ISSUE #276: Show errors from Resume action
### Problem

When the user clicks "Resume" on a paused Job Definition, and the resume action fails, they do not see an error.

### Proposed Solution

On the list and details views, when the resume request returns an error, display the error in the UI.

- [x] List view (#284)
- [ ] Detail view (#286)

### PR DESCRIPTION
**Pull request by jweill-aws**
Fixes #276 by capturing failures of pause, reject, and delete job definition actions and displaying them as alerts.

This only affects the job definitions list. The jobs list's "delete" action is asynchronous; there are no other immediate actions.

reject-pause

### CODE REVIEW

File: src/handler.ts [hunk 1]
```diff
@@ -113,7 +113,7 @@ export class SchedulerService {
         }
       );
     } catch (e: any) {
```
Comment (andrii-i) [inline src/handler.ts:115]: No need to explicitly type error to `any` or `unknown` anywhere in this file

**Review by andrii-i — APPROVED** [review]
Looks and works well. 2 minor style comments for your consideration
