### PR TITLE
Errors for pause, resume, delete in detail page and list view

### LINKED ISSUE #276: Show errors from Resume action
### Problem

When the user clicks "Resume" on a paused Job Definition, and the resume action fails, they do not see an error.

### Proposed Solution

On the list and details views, when the resume request returns an error, display the error in the UI.

- [x] List view (#284)
- [ ] Detail view (#286)

### PR DESCRIPTION
**Pull request by jweill-aws**
Fixes #276. Adds error handlers for the detail page and list view for pause, resume, and delete for jobs and job definitions (except for "delete job" in the list view, which does not make a command call). Displays an alert if an error gets caught. Suppresses the alert on a reload or a new command.

In the video below, the handler is customized to throw errors on all pause and delete job definition requests.

https://user-images.githubusercontent.com/93281816/200671964-4eda0ba6-80f8-4cba-9c76-8001dd066d8b.mov

### CODE REVIEW

File: src/components/job-definition-row.tsx [hunk 1]
```diff
@@ -92,7 +92,7 @@ export function buildJobDefinitionRow(
   forceReload: () => void,
   trans: TranslationBundle,
   ss: SchedulerService,
-  handleApiError: (error: string) => void
+  handleApiError: (error: string | undefined) => void
```
Comment (andrii-i) [inline src/components/job-definition-row.tsx:95]: `handleApiError` accepts `undefined` because it's one of the expected inputs / error object can be `undefined` right? 

(If undefined is used to indicate absence of value and function does not necessary expects to receive undefined otherwise it I think it is better to use `null` to indicate an absence of value s.t. there is a clear differentiation vs 
`undefined` and function would not accept just non-existing/unset field)

File: src/mainviews/detail-view/job-definition.tsx [hunk 2]
```diff
@@ -33,22 +40,28 @@ export interface IJobDefinitionProps {
 
 export function JobDefinition(props: IJobDefinitionProps): JSX.Element {
   const trans = useTranslator('jupyterlab');
+  const [displayError, setDisplayError] = useState<string | undefined>();
```
Comment (andrii-i) [inline src/mainviews/detail-view/job-definition.tsx:43]: Same as in https://github.com/jupyter-server/jupyter-scheduler/pull/286/files#r1017133144

File: src/mainviews/detail-view/job-detail.tsx [hunk 3]
```diff
@@ -62,11 +62,12 @@ export const timestampLocalize = (time: number | ''): string => {
 export function JobDetail(props: IJobDetailProps): JSX.Element {
   const trans = useTranslator('jupyterlab');
   const [downloading, setDownloading] = useState(false);
+  const [displayError, setDisplayError] = useState<string | undefined>();
```
Comment (andrii-i) [inline src/mainviews/detail-view/job-detail.tsx:65]: Same as [comment above](https://github.com/jupyter-server/jupyter-scheduler/pull/286/files#r1017133144)

File: src/mainviews/detail-view/job-detail.tsx [hunk 4]
```diff
@@ -62,11 +62,12 @@ export const timestampLocalize = (time: number | ''): string => {
...
 
   const ss = new SchedulerService({});
 
   const translateStatus = useCallback(
-    (status: Scheduler.Status) => {
+    (status: Scheduler.Status | undefined) => {
```
Comment (andrii-i) [inline src/mainviews/detail-view/job-detail.tsx:70]: Same as [comment above](https://github.com/jupyter-server/jupyter-scheduler/pull/286/files#r1017133144)

**Review by andrii-i — APPROVED** [review]
