### PR TITLE
Validates job name

### LINKED ISSUE #234: Job name validation
### Problem

The job name is not validated; any value, including no value, is accepted for all environments. Sometimes, an environment does not accept certain characters in a job name, causing job runs to fail.

### Proposed Solution

Allow environments to provide validation rules, such as a regular expression (regex) for job names or a list of acceptable characters in job names. Block form submission if a name fails environment validation. Validate the job name upon environment selection or change.

Note that some regex grammars are Turing-complete, introducing a security vulnerability.

### PR DESCRIPTION
**Pull request by jweill-aws**
Fixes #234. Adds validation for jobName in the create form. Sanitizes the input filename by truncating its extension, removing disallowed characters, and substituting `job` (not translated) if nothing is left. Job names are now mandatory.

Screen shots: 

Happy case (valid job name)

image

Empty job name

image

Hyphen in first position

image

Too long

image

Invalid characters

image

### CODE REVIEW

File: src/model.ts [hunk 1]
```diff
@@ -331,7 +334,7 @@ export function convertDescribeJobtoJobDetail(
   return {
     ...emptyCreateJobModel(),
     jobId: describeJob.job_id,
-    jobName: describeJob.name ?? '',
+    jobName: MakeNameValid(describeJob.name ?? ''),
```
Comment (dlqqq) [inline src/model.ts:337]: The name returned from the backend will always be valid, so please revert the changes in this file to avoid conflicts with #258.

File: src/index.tsx [hunk 2]
```diff
@@ -74,13 +75,21 @@ function getSelectedItem(widget: FileBrowser | null): Contents.IModel | null {
...
   }
-  return selectedItem.name;
+  const parts = selectedItem.name.split('.');
+  if (parts.length === 1) {
+    // no extension
+    return parts[0];
+  }
+
+  parts.splice(-1); // Remove the extension
+  return parts.join('.');
```
Comment (dlqqq) [inline src/index.tsx:92]: Why not just always return `parts[0]`? This logic coerces `filename.tar.gz` => `filename.tar` rather than `filename`.

File: src/util/job-name-validation.tsx [hunk 3]
```diff
@@ -0,0 +1,66 @@
+// Utilities to validate and sanitize job names (make them valid)
+
+import { TranslationBundle } from '@jupyterlab/translation';
+
+const jobNameRegex = /^[a-zA-Z0-9._][a-zA-Z0-9._-]{0,62}$/;
+const invalidFirstCharRegex = /^[^a-zA-Z0-9._]/;
+const invalidCharRegex = /[^a-zA-Z0-9._-]/g;
+const maxLength = 63;
```
Comment (dlqqq) [inline src/util/job-name-validation.tsx:8]: These are fine for now, but we should switch to a library that provides a declarative validation API rather than approaching this problem imperatively. See #234 comment.

**Review by dlqqq — CHANGES_REQUESTED** [review]

File: src/index.tsx (hunk 2 above)
Comment (jweill-aws) [reply src/index.tsx:92]: Returning `parts[0]` would coerce `Cloud 3.0 release plan.ipynb` to `Cloud 3`, though

File: src/util/job-name-validation.tsx (hunk 3 above)
Comment (jweill-aws) [reply src/util/job-name-validation.tsx:8]: Filed #260 for this.

File: src/index.tsx (hunk 2 above)
Comment (dlqqq) [reply src/index.tsx:92]: Hmmm, alright, I see arguments can be made for both sides.

**Review by dlqqq — APPROVED** [review]
